spring:
  application:
    name: spring-oauth

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Spring-SSO-App
          jwk-set-uri: http://localhost:8080/realms/Spring-SSO-App/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-oauth
      principle-attribute: preferred_username



server:
  port: 8000


